.github/CODEOWNERS

Added my GitHub username to CODEOWNERS.

CRM-8 - Added my GitHub username to CODEOWNERS

---

management_service/app/DB/README.md

added db directory with readme placeholder.

Crm 29 database create database directory in management service

---

management_service/app/DB/sql/stock/create.sql

added create.sql for stock table; references ingredients table

CRM 31 - Database: Add Create table SQL for stock table

---

management_service/app/DB/sql/employees/create.sql

- Add create table sql for employees table

CRM-35-add-create-table-sql-for-employees-table

---

management_service/app/DB/sql/shiftStockUsage/create.sql

- Add create.sql for shiftStockUsage table

CRM-40-create-table-sql-for-shiftStockUsage-table

---

management_service/app/DB/sql/employeeShifts/create.sql

- Add create.sql for employeeShifts table

CRM-39-create-table-sql-for-employee-shifts-table

---

management_service/app/DB/sql/waste/create.sql

- Add create.sql for waste table

CRM-37-add-create-table-sql-for-waste-table

---

management_service/app/DB/sql/waste/create.sql

-added wasteReason enum
-changed reason data type to enum

CRM-50-database-add-enum-to-the-waste-table

---

management_service/app/routers/index.ts
management_service/app/routers/orders.router.ts
management_service/app/server.ts
management_service/tsconfig.json

First initial router and route. I also changed the TS config to be a bit more strict. :)

DONE: CRM-43

---

management_service/package-lock.json
management_service/package.json

- Ensured the script correctly targets ./build/app/server.js.
- Verified that the command runs without errors.
Testing:
- Ran npm run build followed by npm start to confirm the server starts as expected.

Add start script to package.json for deployment

---

frontend/package-lock.json
frontend/package.json
management_service/.gitignore
management_service/app/DB/prisma/schema.prisma
management_service/package-lock.json
management_service/package.json

- added prisma dev dependency
- added prisma schema file location in package.json

CRM-61: Add Prisma to the management service

---

management_service/app/DB/prisma/migrations/0_init/migration.sql
management_service/app/DB/prisma/schema.prisma
management_service/package-lock.json
management_service/package.json

- Initialize the prisma schema on the express app
- Add the migration.sql file to the prisma/migrations/0_init directory
- Generated the prisma client

CRM-62-server-initialize-the-prisma-on-express

---

management_service/app/DB/prisma/migrations/20250309034957_added_menu_item_is_popular/migration.sql
management_service/app/DB/prisma/schema.prisma

- Edited schema.prisma to include isPopular column in MenuItem table
- Edited ingredient category enum
- Generated migration file for changes
- Ran migration to update database

CRM-79-database-add-is-popular-column-to-menuItem

---

python_services/data/ingredients.csv
python_services/import_ingredients.py

populated the ingredients table by running a script that iterates over the ingredients.csv file. Checks first if there are entries, and asks user to clear the existing data in the event that we need to make changes. Imported 35 ingredients

CRM-69 Populated Ingredients Table 

---

management_service/app/DB/prisma/seed.ts

-appended _ to all variable names in seed.ts

CRM-83-database-fix-prisma-seed-variable-names

---

management_service/app/DB/prisma/seed.ts
management_service/app/routers/orders.router.ts
management_service/app/server.ts

- Remove the variables from the seed.ts file
- Added commments for each upsert
- Fixed prisma import typos

CRM-88-database-remove-db-seed-variables

---

management_service/app/DB/prisma/seed.ts

- Add menuItemsIngredients seed data to seed.ts

CRM-71-database-populate-menuItemsIngredients

---

management_service/app/routers/orders.router.ts

- Update order router to get order items with parameter

CRM-90-server-update-order-routers

---

management_service/app/routers/stock.router.ts

- Updated the GET / stocks endpoint to resolve the "Value not found in enum 'ingredientCategory'" error by ensuring correct selection and data retrieval from the stock and ingredients tables with the help of Sean. Expanded the ingredients selection to include additional fields such as ingredientname, costperunit, servingSize, menuitemingredients, and category. By requesting all ingredients, the frontend can map to the stock array to return each stock that is associated with that ingredient and add the quantity to get the total.
- Code Structure Update: Aligned the stockRouter logic with the revised Prisma schema while preparing for future enhancements like stock status and low stock filtering. Leaving out POST endpoint for future case.

CRM-85 Connect stock-management/inventory endpoints to DB

---

management_service/app/DB/prisma/seed.ts

- Added image urls for menu items to seed.ts upserts
- ran prisma db seed to update the database with the new image urls -

CRM-100-db-add-image-urls-for-menu-items

---

frontend/package-lock.json
frontend/src/app/orderTracking/page.tsx
frontend/src/components/OrderDetailsScreen.tsx
frontend/src/components/OrderReceiptManager.tsx
frontend/src/styles/InteractableOrderItem.module.css
frontend/src/styles/OrderDetailsScreen.module.css
frontend/src/styles/OrderReceiptManager.module.css

This update includes all necessary changes to help smooth out the implementation of the new tracking order page components. It also has a working and styled, model of the order details  screen.

CRM 65 frontend implement order details component and its styles

---

frontend/src/components/IngredientInventoryContainer.tsx

api/ string removed from the Inventory ingredient container.

Updated the fetch string on the IngredientInventory container.tsx. 

---

management_service/app/DB/prisma/migrations/20250318030755_create_expense_table_drop_shift_stock_usage_table/migration.sql
management_service/app/DB/prisma/schema.prisma
management_service/package-lock.json

-added an expense table to be able to track expenses over time periods to calculate profits 
-dropped stockShiftUsage table, as expense table served the original intention for the tables usage better

CRM-111-db-schema-update

---

management_service/app/DB/sql/views/profits/profit_view_one_year.sql
management_service/app/DB/sql/views/profits/profit_view_seven_days.sql
management_service/app/DB/sql/views/profits/profti_view_today.sql

- Add materialized view for profits for today, last 7 days and last year

CRM-114-db-create-materialized-view-for-profits

---

frontend/next.config.ts
frontend/package-lock.json
frontend/src/app/menuManagement/page.tsx
frontend/src/components/MenuItem.tsx
frontend/src/components/MenuManagementContainer.tsx
frontend/src/styles/MenuManagementContainer.module.css

- Added fetch hook to menuManagement page
- Modified MenuItem component to display data from backend
- Modified MenuManagementContainer to display data according to category chosen
- Modified MenuManagementContainer CSS to display category buttons in a 3 column grid
- Modified next.config.ts to allow for image imports from cloudinary
- Modified MenuManagementContainer to display all menu items when no category is chosen
- Removed button for as its not needed

CRM-112-frontend-connnect-menu-manager-to-backend

---

management_service/app/routers/orders.router.ts

- Added timestamp to completed orders
- fixed put request having extra /, removed slash in useMutation

CRM-115-backend-add-timestamp-to-completed-order

---

frontend/src/app/globals.css
frontend/src/app/orderTracking/page.tsx
frontend/src/app/pos/page.tsx
frontend/src/components/IngredientInventoryContainer.tsx
frontend/src/components/OrderReceiptManager.tsx
frontend/src/components/POS/Cart.tsx
frontend/src/styles/OrderReceiptManager.module.css

This update fixes a few minor things, and adds the POS folder in the components folder.
Fixed an error where there was an extra api/ in the useFetch string inside the inventoryContainer.tsx file. 
Styled the toggle button to change order status in the order receipt Manager.
This update also displays the order total.
I've also added the new styling for the mark order button in the respective css module.

Crm 113 fe pos create a cart component

---

management_service/app/DB/prisma/schema.prisma
management_service/app/DB/sql/stock/stockUpdateLoop.sql
management_service/app/routers/orders.router.ts

- Add stockUpdateLoop.sql
- Created a function on the db to update stock
- Function looks for oldest record that is not expired and subtracts the quantity from that record until zero. Then moves to the next oldest non expired record and continues until the quantity needed for menu item is met.

CRM-116-db-stop-stock-update-code-from-negative

---

frontend/src/app/settings/page.tsx
frontend/src/components/NavigationTabs.tsx
frontend/src/components/ProfileSettings.tsx
frontend/src/components/StaffDetailsModal.tsx
frontend/src/components/StaffDirectory.tsx

created the staff info modal that displays staff information; hard coded the staff comments with random algorithm.

CRM 99-create staff info modal

---

management_service/app/DB/prisma/migrations/20250319050013_add_bulk_order_quantity_column/migration.sql
management_service/app/DB/prisma/schema.prisma
management_service/app/routers/stock.router.ts

- Add bulkOrderQuantity column to stock table
- Created create stock post endpoint
- Added db calls to create new stock and accompanying expense record

Crm 117 backend setup create stock endpoint

---

management_service/app/routers/metrics.router.ts

- Fix picture url issue in metrics db calls

CRM-124-backend-fix-picture-url-issue

---

frontend/src/app/productivityMetrics/page.tsx
frontend/src/components/ProductivityNavigationTabs.tsx

Created simple navigation tabs for prod & waste metrics

CRM-123-created navigation tabs for productivity metrics for prod & waste

---

frontend/src/app/globals.css
frontend/src/app/pos/page.tsx
frontend/src/components/HomePage.tsx
frontend/src/components/POS/Cart.tsx
frontend/src/components/SideNavBar.tsx

This update has almost all the functionality an mvp POS needs. Items can be added to the cart and they stack when trying to add it multiple times or when clicking the plus sign. The total is calculated instantly, and the items can be removed all at once or separately. 
preview 1
preview 2
preview 3

Crm 113 fe pos create a cart component 2

---

frontend/src/app/productivityMetrics/page.tsx
frontend/src/components/ProductivityMetrics.tsx
frontend/src/components/ProductivityNavigationTabs.tsx

Created the productivity metrics component and added some color to differentiate the data; currently using data from the backend

CRM-122 create productivity metrics component

---

frontend/src/components/OrderDetailsScreen.tsx
frontend/src/styles/Footer.module.css
frontend/src/styles/OrderDetailsScreen.module.css

This update hides the footer for mobile devices, and implements the blurred background effect for the order details modal.j It now works as intended.

Crm 131 fe make order details screen close and cover the screen

---

frontend/src/app/globals.css
frontend/src/components/MenuItem.tsx
frontend/src/components/MenuManagementContainer.tsx
frontend/src/components/ViewMenuItemModal.tsx

This PR updates the menu manager with a modal that appears when an item is clicked. This displays the info of said item.

CRM-136-fe-implement-a-menu-item-details-modal-for-the-menu-manager

---

frontend/src/components/SideNavBar.tsx

This PR aims to remove the sidebar from pages that shouldn't have it.

Crm 139 fe dont show the navigation bar in certain pages

---

frontend/src/components/IngredientInventoryContainer.tsx
management_service/app/routers/stock.router.ts

- Added button to simulate ordering more inventory from supplier
- Added confirmation modal to confirm order
- Edited order router to handle order requests
- Made a fix to a small bug in the expiration date calculation

CRM-140-frontend-add-button-order-more-inventory

---

frontend/src/app/orderTracking/page.tsx
frontend/src/app/pos/page.tsx
frontend/src/components/InteractableOrderItem.tsx
frontend/src/components/OrderReceiptManager.tsx
frontend/src/components/POS/Cart.tsx

Functionality for the buy button has been added back.

Crm 155 fe pos add the buy button functionality back

---

frontend/src/components/MenuManagementContainer.tsx

Fixes double scroll bars in the menuManager

CRM_159-Fix-double-scroll-bars

---

README.md

Updated the README.md file to include details from the overview of the project to the structure of the application.

CRM-137-Create-README.md

---

frontend/src/app/svgIcons.tsx
frontend/src/components/TimeDropdown.tsx
frontend/src/styles/TimeDropdown.module.css

Updated the styling for the completed orders screen so that it would match the rest of the app. Styles are also now in the TimeDropdown.module.css file.

CRM-153 Update styling on the Completed Orders screen

---

frontend/src/app/orderTracking/page.tsx
frontend/src/app/pos/page.tsx
frontend/src/components/InteractableOrderItem.tsx
frontend/src/components/OrderReceiptManager.tsx
frontend/src/components/POS/Cart.tsx
frontend/src/styles/Cart.module.css
frontend/src/styles/InteractableOrderItem.module.css
frontend/src/styles/OrderReceiptManager.module.css

This PR addresses a good amount of problems, and implements some new features.
Features:
Modals for both cancelling an order or confirming a purchase on the POS page.
Fixes:
1.Orders are now auto removed from the current orders container once they've been marked as complete.
2.The font sizes for the order receipt manager have been overhauled to better match the styling of the brand to keep everything consistent.  
3.Added responsiveness to the current orders components.

Crm 147 fe pos add modal screens order successfully placed canceled

---

frontend/src/app/globals.css
frontend/src/app/pos/page.tsx
frontend/src/styles/Cart.module.css
frontend/src/styles/MenuItem.module.css
frontend/src/styles/MenuManagementContainer.module.css
frontend/tailwind.config.ts

This fix addresses most of the pain points with the POS items and its cart component.
These are the fixes:
1. Fixed positioned buttons now display above everything else.
2. Translate instead of margin to make the buttons slide into frame when adding items to cart implemented.
3. The cart not visible on mobile devices when the page is visited.
4. Added a slide in animation for the cart component.
5. Made items 1 column for mobile but take all the space available.

Crm 173 fe pos UI fixes mobile

---

management_service/app/routers/index.ts
management_service/app/routers/predictiveprep.router.ts
management_service/app/server.ts

Created the predictive prep router and the forecast GET All endpoint, if called it will return with this set of data:
Updated readme with proper tech stack in the Technologies Used category

CRM-162-Backend-Create-predictive-prep-endpoints and updated README.md

---

README.md

Updated list of technologies/tools used and updated code blocks

CRM-185-Update-README-with-new-tech-and-tools

---

frontend/src/components/SplashScreen.tsx
frontend/src/styles/OrderTracking.module.css
frontend/src/styles/ViewMenuItemModal.module.css

Splash screen responsiveness for smaller devices, z index fixes for the menu management page and that's all.

Crm 184 disable vertical scrolling in modals more mobile responsiveness

---

frontend/package-lock.json
frontend/package.json
frontend/src/app/chatbot-admin/page.tsx
frontend/src/app/configs/chatbot-context.tsx
frontend/src/app/configs/chatbotConfig.ts
frontend/src/app/layout.tsx
frontend/src/components/Chatbot.tsx

CRM-187 created Dina, Dine Flow's little chatbot

---

frontend/src/components/SideNavBar.tsx

final buttons for the home menu

Crm 188 fe make home button show sub menu for smaller screens
